### ISSUE TITLE
Labels wrong in file parsing -> enemies tab

### ISSUE THREAD

**Issue by andhen** [RedFantom/gsf-parser#114]
In the example pictures, the labels on the enemies tab are switched. The data under "damage taken" sums up to 5509 while "damage dealt" sums up to 21619, which is exactly the opposite of what the summary tab says. As can be seen in the screenshot from the match, the summary page (sadly for me) is correct.

![enemies_page](https://user-images.githubusercontent.com/3896860/28801349-63e7eba4-7651-11e7-9774-9fcfc0d62966.png)
![match_ending](https://user-images.githubusercontent.com/3896860/28801350-63e9ebac-7651-11e7-8dd5-744afafba0a8.png)
![stats_page](https://user-images.githubusercontent.com/3896860/28801351-63ed0e9a-7651-11e7-97ea-0f0246c694c7.png)

**Comment by Zarainia** [comment]
You are Withon, right? (There must be a way to tell, but I don't know it.)

Anyways, it seems that switching `enemydamaget` and `enemydamaged` in `parse.parse_spawn` makes everything add up correctly. I don't know if anything else is affected by those variables however.

**Comment by RedFantom** [comment]
@Zarainia: While switching it may solve the apparent problem, it would create problems elsewhere in the program indeed, as quite a bit of functions depend on the `parsing.parse.parse_spawn` function. Switching it in the `frames.fileframe.update_widgets_spawn` function would be a better solution.

@andhen: The problem may actually simply be a difference in understanding instead of an actual problem in the code. See, the damage dealt in the statistics tab is the amount of damage you dealt to enemies, and damage taken the amount of damage you took from enemies. In the enemies tab, the damage dealt column contains the amounts of damage the enemies dealt to you and the damage taken column contains the amount of damage taken from you.
If I am correct, then the columns actually do display the correct amounts.

However, as it turns out this is not as obvious as I thought it would be, so perhaps the description should be extended, especially as it also is not mentioned it in the [wiki](https://github.com/RedFantom/GSF-Parser/wiki/File-Parsing).

**Comment by Zarainia** [comment]
Hmm yes, that does make sense, though it could be taken either way. Maybe adding a word like "Damage dealt by" or "Damage deal to" depending on which scheme you want?

**Comment by RedFantom** [comment]
This was implemented and merged in already, so I'm now closing this issue.
