### ISSUE TITLE
Incorrect file name used in file_update when file is selected

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#28]
Combat log files cannot be selected by clicking on them. Error message is shown below. 

![debug](https://cloud.githubusercontent.com/assets/14959769/22849557/74e08c4c-efcc-11e6-91f0-e9742d8599cb.JPG)

**Comment by RedFantom** [comment]
This problem was caused by commit 9d21f55, in which I changed the way files are listed in the `Listbox`. By using a dictionary, a string containing both the date and the time can be exchanged for the actual file name. However, I forgot to add the dictionary operation to the `except` clause that was added for #19. With commit 07e8697, the issue is fixed with an added dictionary operation.
