### ISSUE TITLE
Cannot stop real-time parsing. 

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#54]
When I press "stop real-time parsing" after I have turned it on, a window is displayed like this. 

![image](https://cloud.githubusercontent.com/assets/14959769/23177604/5c8ba822-f835-11e6-9b27-e9302ed8bbea.png)

It never completes the stopping, and nothing in the window moves. The only way to stop it is to close the program.

**Comment by RedFantom** [comment]
Are you sure you have used `git pull` or the synchronization option in the GitHub desktop client to get the solution for issue #23 that I pushed in commit 3feab32? This issue seems very similar, and you are running Windows 10, which should make the GSF Parser not call `add_files()` at all when stopping real-time parsing, while it seems your version still does as you have the `splash_screen` visible. Of course, it might be that the platform check does not work correctly. Could you check this for me?

**Comment by Zarainia** [comment]
Not sure what you mean exactly by "git pull" (I'm new to this stuff), but I downloaded the files from the "master" branch this morning, which should have the latest changes?

**Comment by RedFantom** [comment]
If you downloaded them this morning, then it should work indeed, as the commit was published a while ago and merged into the `master`-branch. This probably means that the platform detection does not always work. I will investigate and if necessary use the additional Python module `platform` to increase the reliability of the detection.

**Comment by RedFantom** [comment]
@Zarainia: Could you run the `platform` branch for me and see what it prints out as "Detected Windows version"? It uses `platform.release()` to detect, and it should just print `10`, but maybe Microsoft changed the release along the way to `10.1` in secret or something?

**Comment by Zarainia** [comment]
Oh, that's weird. It detects it as "post2008Server". Might be because I'm using the "insider preview" version of Windows 10? But I only enabled that recently (a couple of days ago, maybe) and I had the same issue before with regular "windows 10 home". 

![image](https://cloud.githubusercontent.com/assets/14959769/23217374/00d1633e-f8e7-11e6-8e2f-cbc57d0c88d8.png)

**Comment by RedFantom** [comment]
That is probably indeed the source of the problem. It might very well be that the "Insider Preview", because it has so many big updates, does not have a platform release version. Because Windows 7 and Windows Server 2008 are based on the same kernel, of which the kernel for Windows 10 is derived, it just detects that this is a version later than Windows 7. That you were experiencing this issue before can logically be explained with issue #23. I will add this to the `platform` branch, could you then try running again?

**Comment by Zarainia** [comment]
I tried it, but unfortunately the same thing is still happening.

**Comment by RedFantom** [comment]
Oh, it's `post2008Server` and not `post2008server`, right... I'll change that again.

**Comment by Zarainia** [comment]
Hmm it may have worked the first time I ran it, but it doesn't seem to be working now.

**Comment by RedFantom** [comment]
Now I'm absolutely confused. Give me a few moments to try to make it work by using `lower()`.

**Comment by RedFantom** [comment]
@Zarainia Could you try again now it has the `lower()` function on both of the terms of the comparison? It's on the branch `platform`.

**Comment by Zarainia** [comment]
No loading bar, but it works fine, now.

**Comment by RedFantom** [comment]
OK, that's good to hear! The loading bar is created by `add_files()` which updates the list of files in the file frame. However, for an unknown reason (probably due to IO usage or something) it doesn't work on Windows 10 when real-time parsing. On Windows 7 and lower it works fine. Still, with the new refresh button in the UI it's not really necessary to call it anymore, so now it's only called on Windows 7. I'm glad it works now!
