### ISSUE TITLE
Parser detects match as ended when non-GSF effect is applied

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#70]
Here is a screenshot of a few matches occurring within a minute. 

![too-man-matches](https://cloud.githubusercontent.com/assets/14959769/23824722/b1c63862-0649-11e7-8994-a8b7fa4151a0.JPG)

And here is the combatlog in question. 

[combat_2017-03-10_21_31_41_436800.txt](https://github.com/RedFantom/GSF-Parser/files/835916/combat_2017-03-10_21_31_41_436800.txt)

What I think happened was the parser detected the rakghoul infection effects (I hadn't logged onto my character since the last event, so it still had it) that continued to be applied during the GSF match and assumed the match had ended (my character also died when I was in a match and I had the popup over my screen the entire time, but that's an issue for BioWare lol). Could probably be fixed by changing how matches are split (I've noticed there is always Safe Login Immunity when exiting the match, though maybe not if you just close SWTOR?), even though it's probably not a common occurrence.

**Comment by RedFantom** [comment]
There are safe-guards in the splitting of files against such events, but because in some places you have now have three or more events that are not GSF events in the middle of the match the splitting function thinks the match has ended. This should be easy enough to fix by just skipping the events with `Infection` or `Coughing Fits`...
